### PR TITLE
added ram files

### PR DESCRIPTION
**Pull request by sriram-techie**
Added ram files.

### CODE REVIEW

**Comment by sriram182000** [comment]
> Added ram files.

Are they necessary?

**Comment by sriram-techie** [comment]
> > Added ram files.
> 
> Are they necessary?

yes needed now please approve

**Review by sriram182000 — APPROVED** [review]

**Comment by sriram182000** [comment]
Approving

**Comment by sriram-techie** [comment]
Added ram files.

**Pull request merged**
